version: "3.3"
   
services:
  http:
    volumes:
      - ./http/src/:/src/
    build: 
      context: http
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: bash -c "cd /src && python3 -m http.server 8000"
    
  db:
    build: 
      context: postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  web:
    volumes:
      - ./restlin/src/:/code/src/
    build:
      context: restlin
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - db

